[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/gen2brain/go-unarr"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
  name = "github.com/gen2brain/go-unarr"
  unused-packages = false
